// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOxp5wK_KdrSkcDzg2oCIwsP7rl3osg3w',
    appId: '1:598470065462:web:d46aaaf26d58068f4ec797',
    messagingSenderId: '598470065462',
    projectId: 'laze-app-test1',
    authDomain: 'laze-app-test1.firebaseapp.com',
    storageBucket: 'laze-app-test1.firebasestorage.app',
    measurementId: 'G-ET14F3W025',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmtUnr3xfbxZ9ZawX_opQySpBDMfzkwRc',
    appId: '1:710682536364:android:2b2f7fe349d45964d93209',
    messagingSenderId: '710682536364',
    projectId: 'laza-final-project-2025',
    storageBucket: 'laza-final-project-2025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfZAcN8twvIYKjEhKz6MbLEAXaF2cUxGc',
    appId: '1:598470065462:ios:034d948fd1e738d04ec797',
    messagingSenderId: '598470065462',
    projectId: 'laze-app-test1',
    storageBucket: 'laze-app-test1.firebasestorage.app',
    iosBundleId: 'com.example.lazaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfZAcN8twvIYKjEhKz6MbLEAXaF2cUxGc',
    appId: '1:598470065462:ios:034d948fd1e738d04ec797',
    messagingSenderId: '598470065462',
    projectId: 'laze-app-test1',
    storageBucket: 'laze-app-test1.firebasestorage.app',
    iosBundleId: 'com.example.lazaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDOxp5wK_KdrSkcDzg2oCIwsP7rl3osg3w',
    appId: '1:598470065462:web:44f8a11fcb82dcf24ec797',
    messagingSenderId: '598470065462',
    projectId: 'laze-app-test1',
    authDomain: 'laze-app-test1.firebaseapp.com',
    storageBucket: 'laze-app-test1.firebasestorage.app',
    measurementId: 'G-PF5HW4WYGL',
  );

}